In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn

## Preview Dataset

In [70]:
dataset_1 = pd.read_csv('../data/cleveland.csv')
dataset_1.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,label
0,63,1,1,145,233,1,2,150,0,2.3,3,0,6,A
1,37,1,3,130,250,0,0,187,0,3.5,3,0,3,A
2,41,0,2,130,204,0,2,172,0,1.4,1,0,3,A
3,56,1,2,120,236,0,0,178,0,0.8,1,0,3,A
4,57,0,4,120,354,0,0,163,1,0.6,1,0,3,A

In [56]:
dataset_2 = pd.read_csv('../data/glass.csv')
dataset_2.head()

        RI     Na    Mg    Al     Si     K    Ca   Ba   Fe label
0  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0     A
1  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0     A
2  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0     A
3  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0     A
4  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0     A

## Check tipe Data

In [62]:
check_type_1 = dataset_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trestbps  303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalach   303 non-null    int64
 8   exang     303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64
 11  ca        303 non-null    int64
 12  thal      303 non-null    int64
 13  label     303 non-null    object
dtypes: float64(1), int64(12), object(1)
memory usage: 33.3+ KB

In [63]:
check_type_2 = dataset_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 214 entries, 0 to 213
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   RI      214 non-null    float64
 1   Na      214 non-null    float64
 2   Mg      214 non-null    float64
 3   Al      214 non-null    float64
 4   Si      214 non-null    float64
 5   K       214 non-null    float64
 6   Ca      214 non-null    float64
 7   Ba      214 non-null    float64
 8   Fe      214 non-null    float64
 9   label   214 non-null    object
dtypes: float64(9), object(1)
memory usage: 16.8+ KB

## Check Duplikasi

In [67]:
check_duplicate = dataset_1.duplicated().sum()
print(f"Jumlah dataset ke 1 duplikat {check_duplicate}")

Jumlah dataset ke 1 duplikat 0

In [66]:
check_duplicate = dataset_2.duplicated().sum()
print(f"Jumlah data ke 2 duplikat {check_duplicate}")

Jumlah data ke 2 duplikat 1

## Check Data Hilang

In [68]:
check_null = dataset_1.isna().sum()
if check_null.sum() > 0:
    print(f"\nKolom dengan Missing Values dataset 1:")
    print(f"{check_null[check_null > 0]}")
else:
    print(f"Tidak ditemuka data kosong atau Null dataset 1")

Tidak ditemuka data kosong atau Null dataset 1

In [69]:
check_null = dataset_2.isna().sum()
if check_null.sum() > 0:
    print(f"\nKolom dengan Missing Values pada dataset 2:")
    print(f"{check_null[check_null > 0]}")
else:
    print(f"Tidak ditemuka data kosong atau Null pada dataset 2")

Tidak ditemuka data kosong atau Null pada dataset 2